source 'https://rubygems.org'

ruby '3.2.2' 
gem 'sinatra',            '2.1.0'
#gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'sinatra-reloader'
gem 'slim',               '3.0.8'
gem 'thin',               '1.8.1'
gem 'iso_country_codes'
gem 'pg'
gem 'typst'
gem 'activerecord-postgresql-adapter'
#gem 'chartkick'
gem 'groupdate'
gem 'activerecord', '~> 7.0', '>= 7.0.4.2'
gem 'sinatra-activerecord'
gem 'rake', '~>13.1.0'
gem 'content_disposition', '~> 1.0'
gem 'rainbow'
gem 'matrix'
gem 'require_all'
gem 'combine_pdf', 		'1.0.22'
#gem 'open-uri'
gem 'prawn'
gem 'prawn-table', '~> 0.1.0'
gem 'bidi'
gem 'rubyXL'
gem 'pandoc-ruby'
gem 'os'
#gem "sqlite3", "~> 1.6"
