source 'https://rubygems.org'

#require 'os'
ruby '3.3'
gem 'sinatra',            '2.1.0'
#gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'sinatra-reloader'
gem 'slim',               '3.0.8'
#gem 'thin',               '1.8.1'
gem 'localhost'


gem 'puma'
gem 'pg', '~> 1.5', '>= 1.5.4'
gem 'redcarpet'
gem 'rb_sys'
#gem 'typst' #if OS.mac?
gem 'activerecord-postgresql-adapter'
gem 'groupdate'
gem 'activerecord', '~> 7.0', '>= 7.0.4.2'
gem 'sinatra-activerecord'
gem 'rake', '~>13.1.0'
gem 'content_disposition', '~> 1.0'
gem 'rainbow'
gem 'matrix'
gem 'require_all'
gem 'clipboard', '~> 1.3', '>= 1.3.6'
gem 'ffi', '~> 1.16', '>= 1.16.3'
gem 'whenever'
#gem 'combine_pdf', 		'1.0.22'
gem 'prawn'
gem 'prawn-table', '~> 0.1.0'
gem 'bidi'
gem 'rubyXL'
gem 'pandoc-ruby'
gem 'os'
gem 'github-markup'
gem 'commonmarker'
gem 'rack-ssl-enforcer'
gem 'encrypted_cookie'
gem 'google_calendar'
gem 'solargraph'
