source 'https://rubygems.org'

ruby '3.1.2' 
gem 'sinatra',            '2.1.0'
gem 'sinatra-partial'
gem 'sinatra-reloader'
gem 'slim',               '3.0.8'
gem 'thin',               '1.8.1'
gem 'iso_country_codes'
gem 'pg'
gem 'activerecord-postgresql-adapter'
#gem 'rubyzip', 			'= 2.3.2'
gem 'chartkick'
gem 'groupdate'
gem 'libxml-ruby', '~> 2.8'
gem 'aws-sdk-s3', '~> 1'
gem 'activerecord', '~> 7.0', '>= 7.0.4.2'
gem 'sinatra-activerecord'
gem 'rake', '~> 10.4', '>= 10.4.2'
gem 'content_disposition', '~> 1.0'
gem 'colorize'
gem 'matrix'
gem 'require_all'
gem 'combine_pdf', 		'1.0.22'
#gem 'open-uri'
gem 'prawn'
gem 'prawn-table', '~> 0.1.0'
gem 'bidi'
gem 'rubyXL'
gem 'caracal', '~> 1.4', '>= 1.4.1'
gem 'pandoc-ruby'
#gem "sqlite3", "~> 1.6"
