default: &default
  adapter: 'postgresql'
  database: 'rpulpo_db'
  encoding: 'utf8' 
  pool: 5
  
development:
  database: 'rpulpo_db'
  adapter: 'postgresql'  
  encoding: 'utf8'
  pool: 5
  username: 'administrador'
  server: 'cb'

  
production:
  database: 'rpulpo_db'
  adapter: 'postgresql'  
  encoding: 'utf8'
  pool: 5
  username: 'administrador'
  server: 'puma'
