--- 
tables_models:
  people: "person"
  personals: "personal"
  studies: "study"
  crs: "crs"
  rooms: "room"
query_aliases: 
  - sacerdotes: "status:2"
  - sacerdote: "status:2"
  - sacd: "status:2"
  - diáconos: "status:1"
  - diaconos: "status:1"
  - diácono: "status:1"
  - diacono: "status:1"
  - diac: "status:1"
  - agd: "n_agd:1"
  - laicos: "status:0"
  - laico: "status:0"
  - cavabianca: "ctr:0"
  - cb: "ctr:0"
  - dep: "ctr:1"
  - fuera: "ctr:3"
  - se han ido: "ctr:3"
  - dirección: "house:0"
  - direccion: "house:0"
  - dir: "house:0"
  - profesores: "house:1"
  - prof: "house:1"
  - pabellón: "house:2"
  - pabellon: "house:2"
  - conferencias: "house:3"
  - altana: "house:4"
  - chiocciolla: "house:5"
  - chio: "house:5"
  - molino: "house:6"
  - mulino: "house:6"
  - borgo: "house:7"
  - ospiti: "house:8"
  - enfermeria: "house:9"
  - enfermería: "house:9"
  - cg: "house:10"
  - normal: "bed:0"
  - larga: "bed:1"
  - reclinable: "bed:2"
  - individual: "bathroom:0"
  - común: "bathroom:0"
  - comun: "bathroom:1"
name_aliases:
  hab: "room"
  habitación: "room"
  habitacion: "room"
  llegada: "arrival"
  salida: "departure"
  name: "full_name"
  nombre: "full_name"
  ropa: "clothes"
  numero: "clothes"
  número: "clothes"
  num: "clothes"
  año: "year"
  grupo: "grupo"
  center: "ctr"
  centro: "ctr"
  n: "n_agd"
  agd: "n_agd"
  prom: "classnumber"
  promocion: "classnumber"
  promoción: "classnumber"
  tel: "phone"
  casa: "house"
  zona: "house"
  piso: "floor"
  planta: "floor"
  cama: "bed"
  colchón: "matress"
  colchon: "matress"
  bath: "bathroom"
  bath: "baño"
  tel: "phone"
  telefono: "phone"
  teléfono: "phone"